version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: copilot_test
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./certs:/certs:ro
    
    depends_on:
      - db
    ports:
      - "8000:8000"
    # SSL cert paths (optional)
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=copilot_test
      - CREATE_TABLES=1
      # SSL certs intentionally not passed to backend to keep backend HTTP

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:443"
      - "5174:80"
    depends_on:
      - backend
    volumes:
      - ./certs:/etc/nginx/certs:ro

  mkcert:
    image: alpine:latest
    entrypoint: ["/bin/sh","/scripts/generate_certs.sh"]
    volumes:
      - ./certs:/certs
      - ./scripts:/scripts:ro
    tty: true

volumes:
  db-data:
